/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anime Studio (https://sketchfab.com/AS-1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colony-b530b732e04f46239add0f1a18df262f
Title: Colony
*/

import { useGLTF } from '@react-three/drei'

export default function ColonyModel(props) {
    const { nodes, materials } = useGLTF('./3d_models/colony.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[134.492, 20.6, -0.601]} scale={[10.015, 20.031, 9.028]}>
                        <mesh castShadow receiveShadow geometry={nodes.Object_288.geometry} material={materials.bulding_base} scale={[1, 1.57, 1]} />
                    </group>
                    <mesh castShadow receiveShadow geometry={nodes.Object_290.geometry} material={materials.base} position={[134.492, -0.529, 23.966]} scale={[20, 0.725, 42]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_292.geometry} material={materials.ground} position={[134.492, 0.4, 2]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_294.geometry} material={materials.Material} position={[134.492, 0.4, 42]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_296.geometry} material={materials.bulding_front} position={[134.492, 8.2, -0.461]} scale={[10.143, 7.607, 10.143]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_298.geometry} material={materials.material_0} position={[134.492, 41.12, -9.539]} scale={[10.015, 0.5, 0.5]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_300.geometry} material={materials.bulding_base} position={[134.492, 40.57, 0]} scale={[8.984, 0.512, 8.984]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_302.geometry} material={materials.window} position={[130.211, 30.088, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_304.geometry} material={materials.material_0} position={[130.211, 34.371, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_306.geometry} material={materials.window_glass} position={[130.208, 34.477, 10.294]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_308.geometry} material={materials.window} position={[139.052, 30.088, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_310.geometry} material={materials.material_0} position={[139.052, 34.371, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_312.geometry} material={materials.window_glass} position={[139.049, 34.477, 10.294]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_314.geometry} material={materials.window} position={[130.211, 18.236, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_316.geometry} material={materials.material_0} position={[130.211, 22.519, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_318.geometry} material={materials.window_glass} position={[130.208, 22.625, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_320.geometry} material={materials.window} position={[139.052, 18.236, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_322.geometry} material={materials.material_0} position={[139.052, 22.519, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_324.geometry} material={materials.window_glass} position={[139.049, 22.625, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_326.geometry} material={materials.raling} position={[134.492, 3.314, 19.946]} scale={[15, 0.378, 0.25]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_328.geometry} material={materials.road_sides} position={[134.492, 1.614, 23.005]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_330.geometry} material={materials.road_sides} position={[134.492, 1.614, 60.972]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_332.geometry} material={materials.material_0} position={[121.01, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_334.geometry} material={materials.material_0} position={[134.519, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_336.geometry} material={materials.material_0} position={[148.051, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_338.geometry} material={materials.bulding_face} position={[134.492, 20.6, 8.948]} scale={[10.124, 20.248, 0.537]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_340.geometry} material={materials.material_0} position={[134.492, 1.121, -9.824]} scale={[10.341, 0.516, 0.516]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_342.geometry} material={materials.tree} position={[149.519, 10.778, -4.45]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_344.geometry} material={materials.tree_base} position={[149.519, 2.355, -4.45]} scale={[0.759, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_346.geometry} material={materials.tree} position={[119.321, 10.778, -4.45]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_348.geometry} material={materials.tree_base} position={[119.321, 2.355, -4.45]} scale={[0.729, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_350.geometry} material={materials.tree} position={[150.368, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_352.geometry} material={materials.tree_base} position={[150.368, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_354.geometry} material={materials.tree} position={[143.15, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_356.geometry} material={materials.tree_base} position={[143.15, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_358.geometry} material={materials.tree} position={[134.674, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_360.geometry} material={materials.tree_base} position={[134.674, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_362.geometry} material={materials.tree} position={[126.528, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_364.geometry} material={materials.tree_base} position={[126.528, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_366.geometry} material={materials.tree} position={[118.846, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_368.geometry} material={materials.tree_base} position={[118.846, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_370.geometry} material={materials.material_0} position={[135.816, 5.794, 10.197]} rotation={[0, 0, -Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_372.geometry} material={materials.material_0} position={[138.315, 10.848, 10.342]} rotation={[0, 0, -Math.PI]} scale={[2.927, 0.651, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_374.geometry} material={materials.material_0} position={[140.73, 5.794, 10.197]} rotation={[0, 0, -Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_376.geometry} material={materials.door} position={[138.232, 5.454, 9.93]} rotation={[0, 0, -Math.PI / 2]} scale={[4.837, 1.915, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_378.geometry} material={materials.window} position={[130.211, 4.615, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.302, 2.434, 0.324]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_380.geometry} material={materials.material_0} position={[139.613, 5.794, 10.38]} rotation={[0, 0, -Math.PI / 2]} scale={[0.609, 0.136, 0.098]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_382.geometry} material={materials.bricks} position={[144.388, 12.469, 6.455]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_384.geometry} material={materials.bricks} position={[144.388, 11.475, 4.667]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_386.geometry} material={materials.bricks} position={[144.388, 10.416, 6.124]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_388.geometry} material={materials.bricks} position={[144.388, 7.105, 0.826]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_390.geometry} material={materials.bricks} position={[128.108, 14.883, 9.631]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_392.geometry} material={materials.bricks} position={[129.598, 13.89, 9.631]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_394.geometry} material={materials.bricks} position={[124.907, 20.037, 9.176]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.744, 1.053]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_396.geometry} material={materials.ground_bricks} position={[149.485, 0.572, -12.582]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_398.geometry} material={materials.ground_bricks} position={[119.26, 0.572, -12.126]} rotation={[0, 0, Math.PI]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_400.geometry} material={materials.lamp} position={[149.07, 7.533, 13.917]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_402.geometry} material={materials.lamp} position={[149.07, 15.157, 13.929]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_404.geometry} material={materials.lamp} position={[120.971, 7.533, 13.917]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_406.geometry} material={materials.lamp} position={[120.971, 15.157, 13.929]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_408.geometry} material={materials.bulding_base} position={[129.525, 42.103, -6.015]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_410.geometry} material={materials['Material.002']} position={[128.533, 41.371, -3.938]} scale={0.419} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_412.geometry} material={materials.matel} position={[129.415, 44.981, 3.447]} scale={1.157} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_414.geometry} material={materials.bulding_base} position={[138.189, 42.103, -6.015]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_416.geometry} material={materials.matel} position={[129.479, 42.53, 3.429]} scale={2.009} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_418.geometry} material={materials.decor} position={[130.73, 41.371, 7.946]} rotation={[Math.PI / 2, 0, 0]} scale={[0.385, 1.201, 0.168]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_420.geometry} material={materials.road_sides} position={[119.389, 1.614, 9.771]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_422.geometry} material={materials.road_sides} position={[149.55, 1.614, 9.771]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_424.geometry} material={materials.material_0} position={[124.539, 33.129, 10.742]} rotation={[0, Math.PI / 2, 0]} scale={[1.335, 3.979, 0.15]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_426.geometry} material={materials.material_0} position={[145.63, 20.126, 9.033]} rotation={[0, Math.PI / 2, 0]} scale={[0.382, 1.218, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_428.geometry} material={materials.window_glass} position={[130.208, 7.844, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.152]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_430.geometry} material={materials.bulding_base} position={[174.271, 20.6, -0.601]} scale={[10.015, 20.031, 9.028]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_432.geometry} material={materials.base} position={[174.271, -0.529, 23.966]} scale={[20, 0.725, 42]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_434.geometry} material={materials.ground} position={[174.271, 0.4, 2]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_436.geometry} material={materials.Material} position={[174.271, 0.4, 42]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_438.geometry} material={materials.bulding_front} position={[174.271, 8.2, -0.461]} scale={[10.143, 7.607, 10.143]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_440.geometry} material={materials.material_0} position={[174.271, 41.12, -9.539]} scale={[10.015, 0.5, 0.5]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_442.geometry} material={materials.bulding_base} position={[174.271, 40.57, 0]} scale={[8.984, 0.512, 8.984]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_444.geometry} material={materials.window} position={[169.99, 30.088, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_446.geometry} material={materials.material_0} position={[169.99, 34.371, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_448.geometry} material={materials.window_glass} position={[169.988, 34.477, 10.294]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_450.geometry} material={materials.window} position={[178.831, 30.088, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_452.geometry} material={materials.material_0} position={[178.831, 34.371, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_454.geometry} material={materials.window_glass} position={[178.829, 34.477, 10.294]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_456.geometry} material={materials.window} position={[169.99, 18.236, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_458.geometry} material={materials.material_0} position={[169.99, 22.519, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_460.geometry} material={materials.window_glass} position={[169.988, 22.625, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_462.geometry} material={materials.window} position={[178.831, 18.236, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_464.geometry} material={materials.material_0} position={[178.831, 22.519, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_466.geometry} material={materials.window_glass} position={[178.829, 22.625, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_468.geometry} material={materials.raling} position={[174.271, 3.314, 19.946]} scale={[15, 0.378, 0.25]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_470.geometry} material={materials.road_sides} position={[174.271, 1.614, 23.005]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_472.geometry} material={materials.road_sides} position={[174.271, 1.614, 60.972]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_474.geometry} material={materials.material_0} position={[160.789, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_476.geometry} material={materials.material_0} position={[174.299, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_478.geometry} material={materials.material_0} position={[187.83, 0.613, 41.361]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_480.geometry} material={materials.bulding_face} position={[174.271, 20.6, 8.948]} scale={[10.124, 20.248, 0.537]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_482.geometry} material={materials.material_0} position={[174.271, 1.121, -9.824]} scale={[10.341, 0.516, 0.516]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_484.geometry} material={materials.tree} position={[189.299, 10.778, -4.45]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_486.geometry} material={materials.tree_base} position={[189.299, 2.355, -4.45]} scale={[0.759, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_488.geometry} material={materials.tree} position={[159.101, 10.778, -4.45]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_490.geometry} material={materials.tree_base} position={[159.101, 2.355, -4.45]} scale={[0.729, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_492.geometry} material={materials.tree} position={[190.148, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_494.geometry} material={materials.tree_base} position={[190.148, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_496.geometry} material={materials.tree} position={[182.93, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_498.geometry} material={materials.tree_base} position={[182.93, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_500.geometry} material={materials.tree} position={[174.453, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_502.geometry} material={materials.tree_base} position={[174.453, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_504.geometry} material={materials.tree} position={[166.308, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_506.geometry} material={materials.tree_base} position={[166.308, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_508.geometry} material={materials.tree} position={[158.626, 4.44, 63.868]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_510.geometry} material={materials.tree_base} position={[158.626, 1.501, 63.868]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_512.geometry} material={materials.material_0} position={[175.596, 5.794, 10.197]} rotation={[0, 0, -Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_514.geometry} material={materials.material_0} position={[178.095, 10.848, 10.342]} rotation={[0, 0, -Math.PI]} scale={[2.927, 0.651, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_516.geometry} material={materials.material_0} position={[180.51, 5.794, 10.197]} rotation={[0, 0, -Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_518.geometry} material={materials.door} position={[178.011, 5.454, 9.93]} rotation={[0, 0, -Math.PI / 2]} scale={[4.837, 1.915, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_520.geometry} material={materials.window} position={[169.99, 4.615, 9.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.302, 2.434, 0.324]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_522.geometry} material={materials.material_0} position={[179.392, 5.794, 10.38]} rotation={[0, 0, -Math.PI / 2]} scale={[0.609, 0.136, 0.098]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_524.geometry} material={materials.bricks} position={[184.167, 12.469, 6.455]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_526.geometry} material={materials.bricks} position={[184.167, 11.475, 4.667]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_528.geometry} material={materials.bricks} position={[184.167, 10.416, 6.124]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_530.geometry} material={materials.bricks} position={[184.167, 7.105, 0.826]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_532.geometry} material={materials.bricks} position={[167.887, 14.883, 9.631]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_534.geometry} material={materials.bricks} position={[169.377, 13.89, 9.631]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_536.geometry} material={materials.bricks} position={[164.687, 20.037, 9.176]} rotation={[0, Math.PI / 2, 0]} scale={[0.551, 0.744, 1.053]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_538.geometry} material={materials.ground_bricks} position={[189.264, 0.572, -12.582]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_540.geometry} material={materials.ground_bricks} position={[159.039, 0.572, -12.126]} rotation={[0, 0, Math.PI]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_542.geometry} material={materials.lamp} position={[188.85, 7.533, 13.917]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_544.geometry} material={materials.lamp} position={[188.85, 15.157, 13.929]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_546.geometry} material={materials.lamp} position={[160.751, 7.533, 13.917]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_548.geometry} material={materials.lamp} position={[160.751, 15.157, 13.929]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_550.geometry} material={materials.bulding_base} position={[169.305, 42.103, -6.015]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_552.geometry} material={materials['Material.002']} position={[168.313, 41.371, -3.938]} scale={0.419} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_554.geometry} material={materials.matel} position={[169.194, 44.981, 3.447]} scale={1.157} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_556.geometry} material={materials.bulding_base} position={[177.969, 42.103, -6.015]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_558.geometry} material={materials.matel} position={[169.259, 42.53, 3.429]} scale={2.009} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_560.geometry} material={materials.decor} position={[170.509, 41.371, 7.946]} rotation={[Math.PI / 2, 0, 0]} scale={[0.385, 1.201, 0.168]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_562.geometry} material={materials.road_sides} position={[159.169, 1.614, 9.771]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_564.geometry} material={materials.road_sides} position={[189.329, 1.614, 9.771]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_566.geometry} material={materials.material_0} position={[164.318, 33.129, 10.742]} rotation={[0, Math.PI / 2, 0]} scale={[1.335, 3.979, 0.15]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_568.geometry} material={materials.material_0} position={[185.409, 20.126, 9.033]} rotation={[0, Math.PI / 2, 0]} scale={[0.382, 1.218, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_570.geometry} material={materials.window_glass} position={[169.988, 7.844, 9.91]} rotation={[Math.PI / 2, 0, 0]} scale={[1.769, 0.438, 3.152]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_572.geometry} material={materials.bulding_base} position={[174.915, 20.6, 132.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.015, 20.031, 9.028]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_574.geometry} material={materials.base} position={[174.915, -0.529, 107.713]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.725, 42]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_576.geometry} material={materials.ground} position={[174.915, 0.4, 129.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_578.geometry} material={materials.Material} position={[174.915, 0.4, 89.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_580.geometry} material={materials.bulding_front} position={[174.915, 8.2, 132.14]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.143, 7.607, 10.143]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_582.geometry} material={materials.material_0} position={[174.915, 41.12, 141.218]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.015, 0.5, 0.5]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_584.geometry} material={materials.bulding_base} position={[174.915, 40.57, 131.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[8.984, 0.512, 8.984]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_586.geometry} material={materials.window} position={[179.196, 30.088, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_588.geometry} material={materials.material_0} position={[179.196, 34.371, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_590.geometry} material={materials.window_glass} position={[179.199, 34.477, 121.385]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_592.geometry} material={materials.window} position={[170.356, 30.088, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_594.geometry} material={materials.material_0} position={[170.356, 34.371, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_596.geometry} material={materials.window_glass} position={[170.358, 34.477, 121.385]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_598.geometry} material={materials.window} position={[179.196, 18.236, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_600.geometry} material={materials.material_0} position={[179.196, 22.519, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_602.geometry} material={materials.window_glass} position={[179.199, 22.625, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_604.geometry} material={materials.window} position={[170.356, 18.236, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_606.geometry} material={materials.material_0} position={[170.356, 22.519, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_608.geometry} material={materials.window_glass} position={[170.358, 22.625, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_610.geometry} material={materials.raling} position={[174.915, 3.314, 111.733]} rotation={[-Math.PI, 0, -Math.PI]} scale={[15, 0.378, 0.25]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_612.geometry} material={materials.road_sides} position={[174.915, 1.614, 108.674]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_614.geometry} material={materials.road_sides} position={[174.915, 1.614, 70.707]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_616.geometry} material={materials.material_0} position={[188.397, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_618.geometry} material={materials.material_0} position={[174.888, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_620.geometry} material={materials.material_0} position={[161.356, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_622.geometry} material={materials.bulding_face} position={[174.915, 20.6, 122.731]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.124, 20.248, 0.537]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_624.geometry} material={materials.material_0} position={[174.915, 1.121, 141.503]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.341, 0.516, 0.516]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_626.geometry} material={materials.tree} position={[159.888, 10.778, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_628.geometry} material={materials.tree_base} position={[159.888, 2.355, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.759, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_630.geometry} material={materials.tree} position={[190.086, 10.778, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_632.geometry} material={materials.tree_base} position={[190.086, 2.355, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.729, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_634.geometry} material={materials.tree} position={[159.039, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_636.geometry} material={materials.tree_base} position={[159.039, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_638.geometry} material={materials.tree} position={[166.257, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_640.geometry} material={materials.tree_base} position={[166.257, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_642.geometry} material={materials.tree} position={[174.734, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_644.geometry} material={materials.tree_base} position={[174.734, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_646.geometry} material={materials.tree} position={[182.879, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_648.geometry} material={materials.tree_base} position={[182.879, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_650.geometry} material={materials.tree} position={[190.561, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_652.geometry} material={materials.tree_base} position={[190.561, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_654.geometry} material={materials.material_0} position={[173.591, 5.794, 121.482]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_656.geometry} material={materials.material_0} position={[171.092, 10.848, 121.337]} rotation={[Math.PI, 0, 0]} scale={[2.927, 0.651, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_658.geometry} material={materials.material_0} position={[168.677, 5.794, 121.482]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_660.geometry} material={materials.door} position={[171.175, 5.454, 121.749]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[4.837, 1.915, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_662.geometry} material={materials.window} position={[179.196, 4.615, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.302, 2.434, 0.324]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_664.geometry} material={materials.material_0} position={[169.795, 5.794, 121.299]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.609, 0.136, 0.098]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_666.geometry} material={materials.bricks} position={[165.02, 12.469, 125.224]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_668.geometry} material={materials.bricks} position={[165.02, 11.475, 127.012]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_670.geometry} material={materials.bricks} position={[165.02, 10.416, 125.555]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_672.geometry} material={materials.bricks} position={[165.02, 7.105, 130.853]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_674.geometry} material={materials.bricks} position={[181.299, 14.883, 122.048]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_676.geometry} material={materials.bricks} position={[179.809, 13.89, 122.048]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_678.geometry} material={materials.bricks} position={[184.5, 20.037, 122.503]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.744, 1.053]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_680.geometry} material={materials.ground_bricks} position={[159.923, 0.572, 144.261]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_682.geometry} material={materials.ground_bricks} position={[190.147, 0.572, 143.805]} rotation={[-Math.PI, 0, 0]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_684.geometry} material={materials.lamp} position={[160.337, 7.533, 117.762]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_686.geometry} material={materials.lamp} position={[160.337, 15.157, 117.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_688.geometry} material={materials.lamp} position={[188.436, 7.533, 117.762]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_690.geometry} material={materials.lamp} position={[188.436, 15.157, 117.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_692.geometry} material={materials.bulding_base} position={[179.882, 42.103, 137.694]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_694.geometry} material={materials['Material.002']} position={[180.874, 41.371, 135.617]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.419} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_696.geometry} material={materials.matel} position={[179.993, 44.981, 128.232]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.157} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_698.geometry} material={materials.bulding_base} position={[171.218, 42.103, 137.694]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_700.geometry} material={materials.matel} position={[179.928, 42.53, 128.25]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.009} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_702.geometry} material={materials.decor} position={[178.677, 41.371, 123.733]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.385, 1.201, 0.168]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_704.geometry} material={materials.road_sides} position={[190.018, 1.614, 121.908]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_706.geometry} material={materials.road_sides} position={[159.858, 1.614, 121.908]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_708.geometry} material={materials.material_0} position={[184.869, 33.129, 120.937]} rotation={[0, -Math.PI / 2, 0]} scale={[1.335, 3.979, 0.15]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_710.geometry} material={materials.material_0} position={[163.778, 20.126, 122.646]} rotation={[0, -Math.PI / 2, 0]} scale={[0.382, 1.218, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_712.geometry} material={materials.window_glass} position={[179.199, 7.844, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.152]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_714.geometry} material={materials.bulding_base} position={[134.751, 20.6, 132.28]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.015, 20.031, 9.028]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_716.geometry} material={materials.base} position={[134.751, -0.529, 107.713]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.725, 42]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_718.geometry} material={materials.ground} position={[134.751, 0.4, 129.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_720.geometry} material={materials.Material} position={[134.751, 0.4, 89.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 0.2, 20]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_722.geometry} material={materials.bulding_front} position={[134.751, 8.2, 132.14]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.143, 7.607, 10.143]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_724.geometry} material={materials.material_0} position={[134.751, 41.12, 141.218]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.015, 0.5, 0.5]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_726.geometry} material={materials.bulding_base} position={[134.751, 40.57, 131.679]} rotation={[-Math.PI, 0, -Math.PI]} scale={[8.984, 0.512, 8.984]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_728.geometry} material={materials.window} position={[139.032, 30.088, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_730.geometry} material={materials.material_0} position={[139.032, 34.371, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_732.geometry} material={materials.window_glass} position={[139.035, 34.477, 121.385]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_734.geometry} material={materials.window} position={[130.192, 30.088, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_736.geometry} material={materials.material_0} position={[130.192, 34.371, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_738.geometry} material={materials.window_glass} position={[130.194, 34.477, 121.385]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_740.geometry} material={materials.window} position={[139.032, 18.236, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_742.geometry} material={materials.material_0} position={[139.032, 22.519, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_744.geometry} material={materials.window_glass} position={[139.035, 22.625, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_746.geometry} material={materials.window} position={[130.192, 18.236, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.408, 2.737, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_748.geometry} material={materials.material_0} position={[130.192, 22.519, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.124, 1.855, 0.438]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_750.geometry} material={materials.window_glass} position={[130.194, 22.625, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.991]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_752.geometry} material={materials.raling} position={[134.751, 3.314, 111.733]} rotation={[-Math.PI, 0, -Math.PI]} scale={[15, 0.378, 0.25]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_754.geometry} material={materials.road_sides} position={[134.751, 1.614, 108.674]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_756.geometry} material={materials.road_sides} position={[134.751, 1.614, 70.707]} rotation={[-Math.PI, 0, -Math.PI]} scale={[20, 1, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_758.geometry} material={materials.material_0} position={[148.233, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_760.geometry} material={materials.material_0} position={[134.724, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_762.geometry} material={materials.material_0} position={[121.192, 0.613, 90.318]} rotation={[-Math.PI, 0, -Math.PI]} scale={[5, 0.122, 1]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_764.geometry} material={materials.bulding_face} position={[134.751, 20.6, 122.731]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.124, 20.248, 0.537]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_766.geometry} material={materials.material_0} position={[134.751, 1.121, 141.503]} rotation={[-Math.PI, 0, -Math.PI]} scale={[10.341, 0.516, 0.516]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_768.geometry} material={materials.tree} position={[119.724, 10.778, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_770.geometry} material={materials.tree_base} position={[119.724, 2.355, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.759, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_772.geometry} material={materials.tree} position={[149.922, 10.778, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.471, 7.791, 2.471]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_774.geometry} material={materials.tree_base} position={[149.922, 2.355, 136.129]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.729, 2.145, 0.815]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_776.geometry} material={materials.tree} position={[118.875, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_778.geometry} material={materials.tree_base} position={[118.875, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_780.geometry} material={materials.tree} position={[126.093, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_782.geometry} material={materials.tree_base} position={[126.093, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_784.geometry} material={materials.tree} position={[134.57, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_786.geometry} material={materials.tree_base} position={[134.57, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_788.geometry} material={materials.tree} position={[142.715, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_790.geometry} material={materials.tree_base} position={[142.715, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_792.geometry} material={materials.tree} position={[150.397, 4.44, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.17, 2.202, 1.511]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_794.geometry} material={materials.tree_base} position={[150.397, 1.501, 67.811]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.49, 1.302, 0.513]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_796.geometry} material={materials.material_0} position={[133.427, 5.794, 121.482]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_798.geometry} material={materials.material_0} position={[130.928, 10.848, 121.337]} rotation={[Math.PI, 0, 0]} scale={[2.927, 0.651, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_800.geometry} material={materials.material_0} position={[128.513, 5.794, 121.482]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[5.621, 0.563, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_802.geometry} material={materials.door} position={[131.011, 5.454, 121.749]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[4.837, 1.915, 0.443]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_804.geometry} material={materials.window} position={[139.032, 4.615, 121.765]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.302, 2.434, 0.324]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_806.geometry} material={materials.material_0} position={[129.63, 5.794, 121.299]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.609, 0.136, 0.098]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_808.geometry} material={materials.bricks} position={[124.855, 12.469, 125.224]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_810.geometry} material={materials.bricks} position={[124.855, 11.475, 127.012]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_812.geometry} material={materials.bricks} position={[124.855, 10.416, 125.555]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_814.geometry} material={materials.bricks} position={[124.855, 7.105, 130.853]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_816.geometry} material={materials.bricks} position={[141.135, 14.883, 122.048]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_818.geometry} material={materials.bricks} position={[139.645, 13.89, 122.048]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.551, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_820.geometry} material={materials.bricks} position={[144.336, 20.037, 122.503]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 0.744, 1.053]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_822.geometry} material={materials.ground_bricks} position={[119.758, 0.572, 144.261]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_824.geometry} material={materials.ground_bricks} position={[149.983, 0.572, 143.805]} rotation={[-Math.PI, 0, 0]} scale={[1.287, 0.788, 0.788]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_826.geometry} material={materials.lamp} position={[120.173, 7.533, 117.762]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_828.geometry} material={materials.lamp} position={[120.173, 15.157, 117.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_830.geometry} material={materials.lamp} position={[148.272, 7.533, 117.762]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.387, 7.187, 0.536]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_832.geometry} material={materials.lamp} position={[148.272, 15.157, 117.75]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.223} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_834.geometry} material={materials.bulding_base} position={[139.718, 42.103, 137.694]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_836.geometry} material={materials['Material.002']} position={[140.71, 41.371, 135.617]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.419} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_838.geometry} material={materials.matel} position={[139.828, 44.981, 128.232]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.157} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_840.geometry} material={materials.bulding_base} position={[131.054, 42.103, 137.694]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.607, 1.177, 1.336]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_842.geometry} material={materials.matel} position={[139.764, 42.53, 128.25]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.009} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_844.geometry} material={materials.decor} position={[138.513, 41.371, 123.733]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.385, 1.201, 0.168]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_846.geometry} material={materials.road_sides} position={[149.854, 1.614, 121.908]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_848.geometry} material={materials.road_sides} position={[119.694, 1.614, 121.908]} rotation={[-Math.PI, 0, -Math.PI]} scale={[4.861, 0.508, 0.508]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_850.geometry} material={materials.material_0} position={[144.705, 33.129, 120.937]} rotation={[0, -Math.PI / 2, 0]} scale={[1.335, 3.979, 0.15]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_852.geometry} material={materials.material_0} position={[123.614, 20.126, 122.646]} rotation={[0, -Math.PI / 2, 0]} scale={[0.382, 1.218, 1.343]} />
                    <mesh castShadow receiveShadow geometry={nodes.Object_854.geometry} material={materials.window_glass} position={[139.035, 7.844, 121.769]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.769, 0.438, 3.152]} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./3d_models/colony.glb')
